# Generated by Django 4.0.5 on 2022-06-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('contactnumber', models.CharField(max_length=200, null=True)),
                ('Type_of_complaint', models.CharField(choices=[('ITPerson', 'ITPerson'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Gardener', 'Gardener'), ('Other', 'Other')], max_length=200, null=True)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('Time', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Solved'), (2, 'InProgress'), (3, 'Pending')], default=3)),
                ('user_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.profile')),
            ],
        ),
    ]
