# Generated by Django 4.0.5 on 2022-06-25 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('contactnumber', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:Up to 10 digits allowed.', regex='^\\d{10,10}$')])),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
